version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "until nc -z db 5432; do echo Waiting for Postgres...; sleep 2; done;
        python manage.py migrate &&
        python manage.py seed_data &&
        python manage.py create_admin &&
        python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: